#!/bin/bash
#
# Script for building and running unit tests
#
# To Execute: 
#     bash gobuild
#

echo Launching build...

#if bash gradlew -testname=1 clean build jacocoTestReport
if bash gradlew -LoadUnitTest=1 -SaveUnitTest=1 clean build jacocoTestReport
then
  echo Build complete. Test reports are available in build/reports. Launching firefox...
  firefox build/reports/tests/index.html build/reports/jacoco/test/html/index.html &
fi
